'use client'

/**
 * Org Restructuring Proposals — self-reorganizing structure.
 *
 * Surfaces bottlenecks (overloaded agents, idle departments, skill gaps)
 * and restructuring proposals generated by the orchestration engine.
 */

import { PageGrid } from '../../../../components/ui/page-grid'
import { PageHeader } from '../../../../components/ui/page-header'
import { SectionCard } from '../../../../components/ui/section-card'
import { StatCard } from '../../../../components/ui/stat-card'
import { StatusBadge } from '../../../../components/ui/status-badge'
import { trpc } from '../../../../utils/trpc'

const REFRESH = 30_000

export default function OrgRestructuringPage() {
  const analysisQuery = trpc.orchestration.orgAnalysis.useQuery(undefined, {
    refetchInterval: REFRESH,
  })
  const proposalQuery = trpc.orchestration.restructuringProposals.useQuery(undefined, {
    refetchInterval: REFRESH,
  })

  const bottlenecks = (analysisQuery.data ?? []) as Array<{
    type: string
    target: string
    detail: string
    severity: string
  }>
  const proposalList = (proposalQuery.data ?? []) as Array<{
    type: string
    description: string
    status: string
    createdAt: string | Date
  }>
  const implemented = proposalList.filter((p) => p.status === 'implemented').length

  function severityColor(sev: string): 'green' | 'yellow' | 'red' {
    if (sev === 'high' || sev === 'critical') return 'red'
    if (sev === 'medium') return 'yellow'
    return 'green'
  }

  function statusColor(status: string): 'green' | 'yellow' | 'red' | 'blue' {
    if (status === 'implemented') return 'green'
    if (status === 'approved') return 'blue'
    if (status === 'rejected') return 'red'
    return 'yellow'
  }

  function typeColor(type: string): 'red' | 'yellow' | 'blue' | 'purple' {
    if (type === 'overloaded') return 'red'
    if (type === 'idle') return 'yellow'
    if (type === 'missing_skill') return 'purple'
    return 'blue'
  }

  return (
    <div className="p-6 text-slate-50">
      <PageHeader
        title="Org Restructuring"
        subtitle="Self-reorganizing structure — bottleneck analysis + proposals"
      />

      <PageGrid cols="3" className="mb-6">
        <StatCard
          label="Bottlenecks Found"
          value={bottlenecks.length}
          color={bottlenecks.length > 5 ? 'red' : bottlenecks.length > 2 ? 'yellow' : 'green'}
        />
        <StatCard label="Proposals Generated" value={proposalList.length} color="blue" />
        <StatCard label="Proposals Implemented" value={implemented} color="green" />
      </PageGrid>

      <SectionCard title="Current Bottlenecks" className="mb-6">
        {bottlenecks.length === 0 ? (
          <div className="text-xs text-slate-600 py-4 text-center">No bottlenecks detected</div>
        ) : (
          <div className="space-y-2">
            {bottlenecks.map((bn, i) => (
              <div key={i} className="flex items-start gap-3 bg-bg-deep rounded px-3 py-2">
                <StatusBadge label={bn.type.replace('_', ' ')} color={typeColor(bn.type)} />
                <div className="flex-1 min-w-0">
                  <div className="text-xs text-slate-200 font-medium">{bn.target}</div>
                  <div className="text-[10px] text-slate-500 mt-0.5">{bn.detail}</div>
                </div>
                <StatusBadge label={bn.severity} color={severityColor(bn.severity)} />
              </div>
            ))}
          </div>
        )}
      </SectionCard>

      <SectionCard title="Restructuring Proposals">
        {proposalList.length === 0 ? (
          <div className="text-xs text-slate-600 py-4 text-center">No proposals yet</div>
        ) : (
          <div className="space-y-2">
            {proposalList.map((prop, i) => (
              <div key={i} className="flex items-start gap-3 bg-bg-deep rounded px-3 py-2">
                <StatusBadge label={prop.type.replace('_', ' ')} color={typeColor(prop.type)} />
                <div className="flex-1 min-w-0">
                  <div className="text-xs text-slate-200">{prop.description}</div>
                  <div className="text-[10px] text-slate-500 mt-0.5">
                    {new Date(prop.createdAt).toLocaleDateString()}
                  </div>
                </div>
                <StatusBadge label={prop.status} color={statusColor(prop.status)} />
              </div>
            ))}
          </div>
        )}
      </SectionCard>
    </div>
  )
}
